# Generated by Django 4.2.1 on 2023-07-14 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secao_ajuda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='descricao_artigo',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
