# Generated by Django 4.2.1 on 2023-07-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secao_ajuda', '0002_artigo_descricao_artigo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='primeira_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='secao_ajuda/static/imagem_artigo/%Y/%m/%d/<django.db.models.fields.CharField>_imagemUM', verbose_name='Capa do artigo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='segunda_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='secao_ajuda/static/imagem_artigo/%Y/%m/%d/<django.db.models.fields.CharField>_imagemDOIS', verbose_name='Capa do artigo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='segundo_texto',
            field=models.TextField(blank=True, null=True),
        ),
    ]
