# Generated by Django 4.2.1 on 2023-07-14 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secao_ajuda', '0004_alter_artigo_primeira_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='primeira_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/imagens_um/<django.db.models.fields.CharField>/%Y/%m/%d', verbose_name='Capa do artigo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='segunda_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/imagens_dois/<django.db.models.fields.CharField>/%Y/%m/%d', verbose_name='Capa do artigo'),
        ),
    ]
