# Generated by Django 4.2.1 on 2023-07-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secao_ajuda', '0006_alter_artigo_primeira_imagem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='capa_artigo',
            field=models.ImageField(upload_to='imagens/', verbose_name='Capa do artigo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='primeira_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Capa do artigo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='segunda_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/', verbose_name='Capa do artigo'),
        ),
    ]
