# Generated by Django 4.2.1 on 2023-07-17 17:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('secao_ajuda', '0007_alter_artigo_capa_artigo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='capa_artigo',
            field=models.ImageField(upload_to='imagens/capas/%Y/%m/%d/', verbose_name='Capa do artigo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='primeira_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/primeira/%Y/%m/%d/', verbose_name='Capa do artigo'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='segunda_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/segunda/%Y/%m/%d/', verbose_name='Capa do artigo'),
        ),
        migrations.CreateModel(
            name='ArtigosEmDestaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('em_destaque', models.BooleanField(default=False)),
                ('artigo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='secao_ajuda.artigo')),
            ],
        ),
    ]
