# Generated by Django 4.2.1 on 2023-07-18 17:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('secao_ajuda', '0008_alter_artigo_capa_artigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 7, 18, 17, 43, 53, 693416, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='primeira_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/primeira/%Y/%m/%d/', verbose_name='Primeira imagem'),
        ),
        migrations.AlterField(
            model_name='artigo',
            name='segunda_imagem',
            field=models.ImageField(blank=True, null=True, upload_to='imagens/segunda/%Y/%m/%d/', verbose_name='Segunda imagem'),
        ),
    ]
