# Generated by Django 4.2.1 on 2023-08-25 16:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('secao_ajuda', '0010_artigo_em_destaque_alter_artigo_data_publicacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artigo',
            name='data_publicacao',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
