# Generated by Django 4.2.1 on 2023-07-06 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhas', '0002_carteira_delete_planilha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Credor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cred', models.CharField(max_length=2)),
                ('palavras_chaves', models.CharField(max_length=255)),
                ('nome_cred_padrao', models.CharField(max_length=255)),
                ('nome_carteira', models.CharField(max_length=255, verbose_name='Nome')),
            ],
        ),
        migrations.DeleteModel(
            name='Carteira',
        ),
    ]
