# Generated by Django 4.2.1 on 2023-07-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhas', '0003_credor_delete_carteira'),
    ]

    operations = [
        migrations.AddField(
            model_name='credor',
            name='ativa',
            field=models.BooleanField(default=True, verbose_name='Credor ativo'),
        ),
        migrations.AddField(
            model_name='credor',
            name='centro_custo',
            field=models.CharField(default=2, max_length=255),
            preserve_default=False,
        ),
    ]
