# Generated by Django 4.2.1 on 2023-07-06 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilhas', '0004_credor_ativa_credor_centro_custo'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Credor',
            new_name='Carteira',
        ),
    ]
