# Generated by Django 4.2.1 on 2023-07-06 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planilhas', '0005_rename_credor_carteira'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Carteira',
        ),
    ]
