# Generated by Django 4.2.1 on 2023-07-06 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('planilhas', '0006_delete_carteira'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carteira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_cred', models.CharField(max_length=2)),
                ('palavras_chaves', models.CharField(max_length=255)),
                ('centro_custo', models.CharField(max_length=255)),
                ('nome_cred_padrao', models.CharField(max_length=255)),
                ('nome_carteira', models.CharField(max_length=255, verbose_name='Nome')),
                ('ativa', models.BooleanField(default=True, verbose_name='Credor ativo')),
            ],
        ),
    ]
