# Generated by Django 4.2.1 on 2023-10-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planilhas', '0010_alter_carteira_cod_cred'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordDataBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('server', models.CharField(max_length=255)),
                ('database', models.CharField(max_length=255)),
                ('username', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
    ]
