QUERY_META = """
SELECT 
	DISTINCT
	FRENTE,
	TIPO_MEDICAO
FROM 
	HOMOLOGACAO.DBO.ML_07072023_TESTE_METASOPERADORES
WHERE 
	META_ATIVA = 'SIM' AND
    
"""
# INSERT_META = """
# INSERT INTO 
# 	HOMOLOGACAO.DBO.ML_21072023_TESTE_META_VALORPREMIO
# VALUES
# """

INSERT_META = """
INSERT INTO HOMOLOGACAO.DBO.ML_21072023_TESTE_META_VALORPREMIO
(
	[DATA_IMPORT]
      ,[COMP]
      ,[COD_CRED]
      ,[CARTEIRA]
      ,[FRENTE]
      ,[TIPO_MEDICAO]
      ,[TIPO_META]
      ,[CRITERIO_1]
      ,[VLR_PREMIO_1]
      ,[CRITERIO_2]
      ,[VLR_PREMIO_2]
      ,[CRITERIO_3]
      ,[VLR_PREMIO_3]
      ,[CRITERIO_4]
      ,[VLR_PREMIO_4]
      ,[CRITERIO_5]
      ,[VLR_PREMIO_5]
      ,[CRITERIO_6]
      ,[VLR_PREMIO_6]
      ,[CRITERIO_7]
      ,[VLR_PREMIO_7]
      ,[CRITERIO_8]
      ,[VLR_PREMIO_8]
)
VALUES

 """