# Generated by Django 4.2.1 on 2023-08-29 18:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pageuser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_atividade', models.CharField(max_length=125)),
            ],
        ),
        migrations.AlterModelOptions(
            name='acoesrealizadas',
            options={'verbose_name': 'Ação Realizada', 'verbose_name_plural': 'Ações realizadas'},
        ),
        migrations.RemoveField(
            model_name='acoesrealizadas',
            name='nome_acao',
        ),
        migrations.AddField(
            model_name='acoesrealizadas',
            name='acao',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.DO_NOTHING, to='pageuser.atividade'),
            preserve_default=False,
        ),
    ]
